### ISSUE TITLE
Binary & AUR release are broken on Arch Linux. (SSL import error)

### ISSUE THREAD

**Issue by inkstray** [Infinitybeond1/dye#8]
### Even tho OpenSSL is installed, I get the following error:
```
tryzen@archlinux > ~ > 23:19:17 >
-> dye --help
could not import: SSL_get_peer_certificate
```

**Comment by AlphaTechnolog** [comment]
getting same issue here

**Comment by sharflare** [comment]
The aur package seems to be outdated, let me see if updating it solves the problem

**Comment by sharflare** [comment]
Yea updating the aur package to v1.2.1 has solved the issue
